### ISSUE TITLE
内存模块更新

### ISSUE THREAD

**Issue by miracle-74** [Owen-Tian/MAAM-NET#1]
你好,在读了这篇优秀的论文和实现的代码后,我有一些问题想请教你,我在代码里好像没有发现内存模块存储的数据更新的相关代码,请问这部分的代码在哪里,在初始化内存池时,设置的内存块容量为2000,但是论文中说检索到的items数量为几十或者几百,我想知道这个item指的是什么,是内存模块的容量变为了这个数目吗,我好想也没有看到相应的代码,请问你能将这两个部分对应的代码部分给我指出来一下吗,十分感谢你的帮助!!!

**Comment by Owen-Tian** [comment]
1.内存块是以变量初始化的，它的更新是随着网络的反向传播自动进行的，这也是为了减少人工参与，使得内存块中的参数自主学习；
2.文中提到的Items是指经encoder编码的Z中的每一个维度信息特征，经由内存块中的（部分）相似度较高的特征重新整合而成的，items就是指内存块中那几个特征参与了该维度信息特征的重新整合。

**Comment by miracle-74** [comment]
十分感谢您的回复，是否可以这么理解，items项的意思就是指特征z对内存模块进行余弦相似度后，设置了一个阈值，高于这个阈值的匹配概率的内存项就认为参与了特征的读取重建工作，但是在训练的过程中其实内存模块的矩阵大小，行数并没有发生改变。感谢您的解答，祝你工作顺利，学术长青!!!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 晚上11:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Owen-Tian/MAAM-NET] 内存模块更新 (Issue #1)




 
1.内存块是以变量初始化的，它的更新是随着网络的反向传播自动进行的，这也是为了减少人工参与，使得内存块中的参数自主学习；
 2.文中提到的Items是指经encoder编码的Z中的每一个维度信息特征，经由内存块中的（部分）相似度较高的特征重新整合而成的，items就是指内存块中那几个特征参与了该维度信息特征的重新整合。

**Comment by Owen-Tian** [comment]
您理解的完全正确，论文中展示Items数量变化主要是为了体现潜在损失函数Latent Loss对于网络计算量下降的作用，由于不再要求特征Z与经由内存块重新整合的特征Z完全的相似，因此从内存块中检索的Items数量会有明显的下降，侧面体现Latent Loss的有效性。

**Comment by miracle-74** [comment]
> 您理解的完全正确，论文中展示Items数量变化主要是为了体现潜在损失函数Latent Loss对于网络计算量下降的作用，由于不再要求特征Z与经由内存块重新整合的特征Z完全的相似，因此从内存块中检索的Items数量会有明显的下降，侧面体现Latent Loss的有效性。

好的,十分感谢您的回答!
